### ISSUE TITLE
Remaining issues with references

### ISSUE THREAD

**Issue by kcopas** [gbif/doc-sensitive-species-data-generalization#2]
We've done a massive amount of clean-up on the reference list, but there are two items that we need help with:

Is `Saarenmaa H (2005) Sharing and Accessing Biodiversity Data Globally through GBIF` a reference to either of these resources?
- [ ] https://www.researchgate.net/publication/228389662_Sharing_and_accessing_biodiversity_data_globally_through_GBIF
- [ ] https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=82e82f49eb642214aa0cf3dd1e80f94a3ed3d52a 

The dates are different, but is it possible that `NSW (2006) Sensitive Species Data Policy. Department of Environment, Climate Change and Water (DECCW), New South Wales` the same as this document cited in Chapman 2020?
- [ ] DECCW (2009) Sensitive Species Data Policy. New South Wales Department of Environment, Climate Change and Water. https://www.environment.nsw.gov.au/resources/nature/SensitiveSpeciesPolicyDEC09.pdf

**Comment by franastorga** [comment]
In relation to Saarenma citation, both links deliver the same document, which does not explicitly give any date of publication. However, in research gate they mention a date (2005). I guess its better to cite: https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=82e82f49eb642214aa0cf3dd1e80f94a3ed3d52a and not the research gate link, just for formality. But they are, in deed, the same document. 

In relation to the second issue, yes, they are also the same document: 
DECCW (2009) Sensitive Species Data Policy. New South Wales Department of Environment, Climate Change and Water. https://www.environment.nsw.gov.au/resources/nature/SensitiveSpeciesPolicyDEC09.pdf
NSW (2006) Sensitive Species Data Policy. Department of Environment, Climate Change and Water (DECCW), New South Wales. (as cited in the current version of this sensitive sepcies report)

**Comment by kcopas** [comment]
Okay, so turned up the fact that Saarenmaa is a conference paper/proceeding at the 2005 ESRI UC. Given that none of the multiple references have a PID, I assigned it a DOI and deposited a PDF in Zenodo with an additional reference back to the ESRI abstract. Should make that one easier to find for anyone who's interested now.
