### ISSUE TITLE
problem DOIs

### ISSUE THREAD

**Issue by kcopas** [gbif/doc-sensitive-species-data-generalization#3]
There are two DOIs in the reference list that you would swear are malformed, but dropping them into an address, they actually do work. However, they don't work in our builds of the document. Tagging you, @MattBlissett , in hope that you know a workaround that lets us escape the chaos caused by brackets, parens and the rest of the garbage in these identifiers.

The lines at issue are (with accurate DOIs in code):

- Bailey LL, Simons TR, & Pollock KH (2004) Estimating detection probability parameters for Plethodon salamanders using the robust capture–recapture design. Journal of Wildlife Management 68(1): 1–13. `https://doi.org/10.2193/0022-541X(2004)068[0001:EDPPFP]2.0.CO;2`
- Schlaepfer MA, Hoover C & Dodd CK (2005) Challenges in Evaluating the Impact of the Trade in Amphibians and Reptiles on Wild Populations. BioScience 55(3):256. `https://doi.org/10.1641/0006-3568(2005)055[0256:CIETIO]2.0.CO;2`

**Comment by kcopas** [comment]
Mangled display here:
https://docs.gbif-uat.org/sensitive-species-data-generalization/en/#references

**Comment by MattBlissett** [comment]
And to think we avoid 1, I and L in our DOIs to make them easy.

I had to refer to https://docs.asciidoctor.org/asciidoc/latest/macros/link-macro/. A few ways would work, I picked the simplest.

**Comment by kcopas** [comment]
just noting syntax here for ref:
> `link:++https://doi.org/10.2193/0022-541X(2004)068[0001:EDPPFP]2.0.CO;2++`
> `link:++https://doi.org/10.1641/0006-3568(2005)055[0256:CIETIO]2.0.CO;2++`
