### ISSUE TITLE
SINP

### ISSUE THREAD

**Issue by kcopas** [gbif/doc-sensitive-species-data-generalization#5]
I think there's an issue with the draft's parsing of the acronym SINP. While its original name was indeed "Système d’information sur la nature et les paysages" (see [here](https://docs.gbif-uat.org/sensitive-species-data-generalization/en/#organizational-and-nationalsubnational-sensitive-species-data-frameworks), among other places), it nows operates as "Système d’information de l’inventaire du patrimoine naturel" under the ægis of INPN. I can't see any reason to preserve the old version of the name, but flagging it in case I'm overlooking something.

**Comment by andrewrodrigues** [comment]
This name can be updated in the document
