### ISSUE TITLE
Chapman 2010 ref in §2.1

### ISSUE THREAD

**Issue by kcopas** [gbif/doc-sensitive-species-data-generalization#7]
This passage ends by citing something that's not in the references:

> However, the term UNC may signal spatial uncertainties of short distances that may not act as efficient generalizations in terms of obfuscation of species localities. In fact, when exploring the generalizations of the records related to threatened and near threatened sensitive species, nearly half of the occurrences that made use of UNC term had uncertainties of less than 500 metres, which do not comply with most of the recommended buffer distances provided in guidelines (see `Chapman 2010`)

Is this a typo or something that's genuinely missing?

**Comment by franastorga** [comment]
Reference should be changed to the document of "Current Best Practices for Generalzing Sensitive Species Occurrence Data" (Chapman 2020)

**Comment by franastorga** [comment]
In pages 18-20 and 25 of that document, they give the general recommendations for spatial generalization
