### ISSUE TITLE
Add high-res camera trap photo

### ISSUE THREAD

**Issue by kcopas** [gbif/doc-sensitive-species-data-generalization#9]
The [img directory](https://github.com/gbif/doc-sensitive-species-data-generalization/tree/7507dc8cac51a640be0e6357a613ede7beb4e266/img) now has a high-res version of the camera trap photo used in the guide. 

@MattBlissett could you advise on whether we should simply use it to replace the lower quality one or deploy it in print only?

**Comment by MattBlissett** [comment]
Hi,

As the image is large, I suggest using a downscaled version for the web view.

**Comment by kcopas** [comment]
Great, thanks. I'll look at our priors to get the high-res version added to the PDF, then.
